= Connectivity

:doctype: article
:encoding: utf-8
:lang: en
:toc: right
:numbered!:
:figure-caption!:
:description: This document is part of the modeling guidelines for the NBNL Profile Group.
:url-repo: https://github.com/Netbeheer-Nederland/doc-modeling-guidelines
:domain: modellen.netbeheernederland.nl
:uri: https://{domain}/modeling-guidelines/points
:version: {page-component-display-version}

Author:: mailto:robbert.hardin@alliander.com[Robbert Hardin] (Alliander)
//Editors::
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander) +
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander)https://intranet.alliander.com/event/view/45715445/weten-wat-je-wilt-13-7-april-2026-onlinek

Version:: {version}

Feedback::
https://github.com/Netbeheer-Nederland/doc-modeling-guidelines/issues[Issue on GitHub] (https://github.com/Netbeheer-Nederland/doc-modeling-guidelines[`Netbeheer-Nederland/doc-modeling-guidelines`])

---

== Introduction

The electrical grid is an interconnected network for electricity delivery from power producers to consumers. It consists of *power plants*, *electric power transmission* to carry power over long distances, *electric power distribution* to customers and finally of *electrical substations* that step voltage up or down to enable transmission and distribution. As such they are the humming hearts of the electrical grid.

image::Electricity_grid_simple-_North_America.svg[]

https://commons.wikimedia.org/wiki/File:Electricity_grid_simple-_North_America.svg[Diagram of an electrical grid] (generation system in red, transmission system in blue, distribution system in green).

== A Substation
So what does this humming heart look like? An electrical https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Substation.html[Substation] contains one or more https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/PowerTransformer.html[PowerTransformer]s. A PowerTransformer uses  windings, the so called https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/PowerTransformerEnd.html[PowerTransformerEnd]s, to step up or step down the voltage. In a *step down* PowerTransformer, the PowerTransformerEnd with the highest voltage (https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/BaseVoltage.html[BaseVoltage]) is called the _primary_ PowerTransformerEnd. The other PowerTransformerEnds, with lower voltages,  are called _secondary_, _tertiary_  and so on. Usually it stops at secondary PowerTransformerEnd. 

A collection of equipments (ConductingEquipment, is this a better choice of word?) with the same BaseVoltage is grouped into a https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/VoltageLevel.html[VoltageLevel]. The name VoltageLevel might be confusing, it is not about the voltage level itself, it is about equipments with the same voltage level. There is a VoltageLevel associated to (the BaseVoltage of) the primary PowerTransformerEnd and one associated to the secondary PowerTransformerEnd. And if there is a tertiary PowerTransformerEnd with the same BaseVoltage as the secondary PowerTransformerEnd they form one and the same VoltageLevel (@Arend, is this correct?).  Hence, the number of VoltageLevels does not need to equal the number of PowerTransformerEnds, it really is about the number of BaseVoltages. 

.PowerTransformers
image::PowerTransformers.drawio.svg[]

Besides a *step down* PowerTransformer, there is the aforementioned *step up* PowerTransformer that steps up the voltage (as its name implies). From a CIM-modeling perspective they are equal:

include::partial$connectivity/PowerTransformer.d2[]


== Connecting Substations
Substations are connected by physical cables with https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Joint.html[Joints],  https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Switch.html[Switch]es and other https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/ConductingEquipment.html[ConductingEquipment].

Connecting Substations using ConnectiryNodes, Terminals and TopoligcalNodes. Explaining these are abstractions and they can only exist because of Kirchhoff's Law. 

TSO/DSO so you need SubGeographicalRegion

---

This document includes text from the https://www.ofgem.gov.uk/decision/long-term-development-statement-direction[LTDS Grid Modelling Guidelines], published under the http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/[Open Government License]

