= Connectivity

:doctype: article
:encoding: utf-8
:lang: en
:toc: right
:numbered!:
:figure-caption!:
:description: This document is part of the modeling guidelines for the NBNL Profile Group.
:url-repo: https://github.com/Netbeheer-Nederland/doc-modeling-guidelines
:domain: modellen.netbeheernederland.nl
:uri: https://{domain}/modeling-guidelines/points
:version: {page-component-display-version}

Author:: mailto:robbert.hardin@alliander.com[Robbert Hardin] (Alliander)
//Editors::
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander) +
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander)https://intranet.alliander.com/event/view/45715445/weten-wat-je-wilt-13-7-april-2026-onlinek

Version:: {version}

Feedback::
https://github.com/Netbeheer-Nederland/doc-modeling-guidelines/issues[Issue on GitHub] (https://github.com/Netbeheer-Nederland/doc-modeling-guidelines[`Netbeheer-Nederland/doc-modeling-guidelines`])

---

== Introduction

The electrical grid is an interconnected network for electricity delivery from power producers to consumers. It consists of *power plants*, *electric power transmission* to carry power over long distances, *electric power distribution* to customers and finally of *electrical substations* that step voltage up or down to enable transmission and distribution. As such they are the humming hearts of the electrical grid.

image::Electricity_grid_simple-_North_America.svg[]

https://commons.wikimedia.org/wiki/File:Electricity_grid_simple-_North_America.svg[Diagram of an electrical grid (generation system in red, transmission system in blue, distribution system in green)]

A substation uses transformers to step voltage up or down. This is a picture of a transformer. It is a <trafo xyz of type abc> with serial number 123. This is very useful information when you are a purchaser and you need to purchase a replacement transformer. But as a net engineer you might be interested in its function: stepping voltage up or down. This is (in short) the difference between asset perspective and funtional perspective. More on this in a later part.


{image of a transformer} {single line diagram of a transformer} {CIM-representation of a transformer}

---

This document includes text from the https://www.ofgem.gov.uk/decision/long-term-development-statement-direction[LTDS Grid Modelling Guidelines], published under the http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/[Open Government License]

