= Connectivity

:doctype: article
:encoding: utf-8
:lang: en
:toc: right
:numbered!:
:figure-caption!:
:description: This document is part of the modeling guidelines for the NBNL Profile Group.
:url-repo: https://github.com/Netbeheer-Nederland/doc-modeling-guidelines
:domain: modellen.netbeheernederland.nl
:uri: https://{domain}/modeling-guidelines/points
:version: {page-component-display-version}

Author:: mailto:robbert.hardin@alliander.com[Robbert Hardin] (Alliander)
//Editors::
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander) +
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander)https://intranet.alliander.com/event/view/45715445/weten-wat-je-wilt-13-7-april-2026-onlinek

Version:: {version}

Feedback::
https://github.com/Netbeheer-Nederland/doc-modeling-guidelines/issues[Issue on GitHub] (https://github.com/Netbeheer-Nederland/doc-modeling-guidelines[`Netbeheer-Nederland/doc-modeling-guidelines`])

---

== Introduction

The electrical grid consists of *power plants* that generate electrical power, *electric power transmission* that carry it over long distances, *electric power distribution* that carry it to customers and finally of *electrical substations* that step voltage up or down to enable transmission and distribution. These components form an interconnected network for electricity delivery from power producers to consumers. This document describes *connectivity*; the way CIM models how these components are connected.

== Connectivity Node

CIM uses connectivity nodes (https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/ConnectivityNode.html[cim:ConnectivityNode] for AC and https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/DCNode.html[cim:DCNode] for DC) to model connectivity of equipment. However, connected pieces of (conducting) equipment are not _directly_ associated to such a connectivity node. In stead they are associated _via_ terminals (https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Terminal.html[cim:Terminal] for AC and https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/DCTerminal.html[cim:DCTerminal] for DC):

.Connectivity Node
[d2,svg,theme=4]
----
include::partial$/vars.d2[]
include::partial$/classes.d2[]
include::partial$/connectivity/ConnectivityNode.d2[alt="CIM-based presentation of ConnectivityNode"]
----

A different, more visual representation might look like this:

.Connectivity Node 
image::ConnectivityNode.svg[alt="Artist impression of ConnectivityNode"]

By definition connectivity nodes are points where terminals of conducting equipment are connected together with zero impedance. This enables terminals to be used as  points of connectivity-related measurement in the network such as voltages or phase information (ABC). So, in practice, if you have two terminals associated to a breaker and your measurement at these terminals show different voltages then you know this breaker is open. This is a benefit of modeling connectivity using connectivity nodes via terminals.

.MultiTerminals
image::MultiTerminals.svg[alt="MultiTerminals"]

.Unbalanced
image::Unbalanced.svg[alt="Unbalanced"]

== Cardinality of Terminals

Any terminal is associated to exactly one piece of conducting equipment and it is associated to at mot one connectivity node. On the other hand, any connectivity node can have any number of terminals. Just as any piece of conducting equipment.

.Cardinality
[d2,svg,theme=4]
----
include::partial$/connectivity/Cardinality.d2[alt="Cardinality of Terminals"]
----

=== Caveats

Please note there are some requirements and constraints. You can find them at https://connect.nen.nl/Standard/PopUpHtml?RNR=3659951&search=&Native=1&token=2f83a08b-fd9c-450c-b760-ece017b60721#4.3Requirementsandconstraints[IEC 61970-452 4.3 Requirements and constraints]

==== Constraint 452 Terminal:connection (EQ-profile only)

Terminal-s of the two sides of a two-terminal ConductingEquipment (or any of its subclasses) shall not be connected to the same ConnectivityNode.

==== Requirement 452 ConductingEquipment:connectivity (All profiles)

All subtypes of ConductingEquipment are required to have associations to Terminals. The number of associated Terminals is specified in IEC 61970-301:2020, 4.8.2 "Number of terminals for ConductingEquipment objects." The associated Terminal(s) are not require to have associations to ConnectivityNodes, for instance a ShuntCompensator whose Terminal is not associated to a ConnectivityNode.

==== Number of terminals for ConductingEquipment objects

The following ConductingEquipment classes have two terminals: 

* ACLineSegment,
* DCLineSegment, 
* DCSeriesDevice, 
* DCSwitch (and its specializations), 
* DCChopper, 
* Switch and all its specializations (including Jumper, Fuse, Breaker, Disconnector, LoadBreakSwitch, and Cut), 
* SeriesCompensator and 
* EquivalentBranch. 

The PowerTransformer class typically has two terminals but may also have one or more terminals. For example, a zig-zag connected grounding transformer may have one terminal. Three terminal transformers are commonly used in transmission systems and in special cases transformers may have four, five, or more terminals. All other ConductingEquipment leaf classes (notably also including Clamp and BusbarSection) and DCConductingEquipment have a single terminal.

https://connect.nen.nl/Standard/PopUpHtml?RNR=3638054&search=&Native=1&token=c2ad0bfb-4555-4275-96f3-03f2b39c1616#4.8.2NumberofterminalsforConductingEquipmentobjects[IEC 61970-301:2020, 4.8.2 "Number of terminals for ConductingEquipment objects."]

---

This document includes text from the https://www.ofgem.gov.uk/decision/long-term-development-statement-direction[LTDS Grid Modelling Guidelines], published under the http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/[Open Government License]

