= Connectivity

:doctype: article
:encoding: utf-8
:lang: en
:toc: right
:numbered!:
:figure-caption!:
:description: This document is part of the modeling guidelines for the NBNL Profile Group.
:url-repo: https://github.com/Netbeheer-Nederland/doc-modeling-guidelines
:domain: modellen.netbeheernederland.nl
:uri: https://{domain}/modeling-guidelines/points
:version: {page-component-display-version}

Author:: mailto:robbert.hardin@alliander.com[Robbert Hardin] (Alliander)
//Editors::
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander) +
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander)https://intranet.alliander.com/event/view/45715445/weten-wat-je-wilt-13-7-april-2026-onlinek

Version:: {version}

Feedback::
https://github.com/Netbeheer-Nederland/doc-modeling-guidelines/issues[Issue on GitHub] (https://github.com/Netbeheer-Nederland/doc-modeling-guidelines[`Netbeheer-Nederland/doc-modeling-guidelines`])

---

== Introduction

The electrical grid consists of *power plants* that generate electrical power, *electric power transmission* that carry it over long distances, *electric power distribution* that carry it to customers and finally of *electrical substations* that step voltage up or down to enable transmission and distribution. These components form an interconnected network for electricity delivery from power producers to consumers. This document describes *connectivity*; the way CIM models how these components are connected.

== Connectivity Node

CIM uses connectivity nodes (https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/ConnectivityNode.html[cim:ConnectivityNode]) to model connectivity of equipment. However, connected pieces of (conducting) equipment are not _directly_ associated to such a connectivity node. In stead they are associated _via_ terminals (https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Terminal.html[cim:Terminal]):

.cim:ConnectivityNode
[d2,svg,theme=4]
----
include::partial$/vars.d2[]
include::partial$/legend.d2[]
include::partial$/classes.d2[]
include::partial$/connectivity/ConnectivityNode.d2[alt="CIM-based presentation of ConnectivityNode"]
----

A different, more visual representation might look like this:

.Connectivity Node 
image::ConnectivityNode.svg[alt="Artist impression of ConnectivityNode"]

By definition connectivity nodes are points where terminals of AC conducting equipment are connected together with zero impedance. This enables terminals to be used as  points of connectivity-related measurement in the network such as voltages or phase information (ABC). So, in practice, if you have two terminals associated to a breaker and your measurement at these terminals show different voltages then you know this breaker is open. This is a benefit of modeling connectivity using connectivity nodes via terminals.

.Open Breaker
image::OpenBreaker.svg[alt="Open Breaker"]

---

This document includes text from the https://www.ofgem.gov.uk/decision/long-term-development-statement-direction[LTDS Grid Modelling Guidelines], published under the http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/[Open Government License]

