= Connectivity

:doctype: article
:encoding: utf-8
:lang: en
:toc: right
:numbered!:
:figure-caption!:
:description: This document is part of the modeling guidelines for the NBNL Profile Group.
:url-repo: https://github.com/Netbeheer-Nederland/doc-modeling-guidelines
:domain: modellen.netbeheernederland.nl
:uri: https://{domain}/modeling-guidelines/points
:version: {page-component-display-version}

Author:: mailto:robbert.hardin@alliander.com[Robbert Hardin] (Alliander)
//Editors::
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander) +
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander)https://intranet.alliander.com/event/view/45715445/weten-wat-je-wilt-13-7-april-2026-onlinek

Version:: {version}

Feedback::
https://github.com/Netbeheer-Nederland/doc-modeling-guidelines/issues[Issue on GitHub] (https://github.com/Netbeheer-Nederland/doc-modeling-guidelines[`Netbeheer-Nederland/doc-modeling-guidelines`])

---

== Introduction

Substations are the humming hearts of the electrical grid, an interconnected network for electricity delivery from power producers to consumers. Electrical grids consist of power plants, electrical substations to step voltage up or down, electric power transmission to carry power over long distances, and finally electric power distribution to customers. 

image::Electricity_grid_simple-_North_America.svg[]

https://commons.wikimedia.org/wiki/File:Electricity_grid_simple-_North_America.svg[Diagram of an electrical grid (generation system in red, transmission system in blue, distribution system in green)]

But what does a substation look like. And how do you model a substation?

A substation step voltage up or down. To do so it uses transformers:

{image of a transformer} {single line diagram of a transformer} {CIM-representation of a transformer}




---

This document includes text from the https://www.ofgem.gov.uk/decision/long-term-development-statement-direction[LTDS Grid Modelling Guidelines], published under the http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/[Open Government License]

