= Connectivity

:doctype: article
:encoding: utf-8
:lang: en
:toc: right
:numbered!:
:figure-caption!:
:description: This document is part of the modeling guidelines for the NBNL Profile Group.
:url-repo: https://github.com/Netbeheer-Nederland/doc-modeling-guidelines
:domain: modellen.netbeheernederland.nl
:uri: https://{domain}/modeling-guidelines/points
:version: {page-component-display-version}

Author:: mailto:robbert.hardin@alliander.com[Robbert Hardin] (Alliander)
//Editors::
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander) +
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander)https://intranet.alliander.com/event/view/45715445/weten-wat-je-wilt-13-7-april-2026-onlinek

Version:: {version}

Feedback::
https://github.com/Netbeheer-Nederland/doc-modeling-guidelines/issues[Issue on GitHub] (https://github.com/Netbeheer-Nederland/doc-modeling-guidelines[`Netbeheer-Nederland/doc-modeling-guidelines`])

---

== Introduction

The electrical grid is an interconnected network for electricity delivery from power producers to consumers. It consists of *power plants*, *electric power transmission* to carry power over long distances, *electric power distribution* to customers and finally of *electrical substations* that step voltage up or down to enable transmission and distribution. As such they are the humming hearts of the electrical grid.

image::Electricity_grid_simple-_North_America.svg[]

https://commons.wikimedia.org/wiki/File:Electricity_grid_simple-_North_America.svg[Diagram of an electrical grid (generation system in red, transmission system in blue, distribution system in green)]

== A Substation
So what does this humming heart look like? An electrical https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Substation.html[Substation] contains one or more https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/PowerTransformer.html[PowerTransformer]s. A PowerTransformer uses  windings, the so called https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/PowerTransformerEnd.html[PowerTransformerEnd]s, to step up or step down the voltage. In a *step down* PowerTransformer, the PowerTransformerEnd with the highest voltage (https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/BaseVoltage.html[BaseVoltage]) is called the _primary_ PowerTransformerEnd. The other PowerTransformerEnds, with lower voltages,  are called _secondary_, _tertiary_  and so on. Usually it stops at secondary PowerTransformerEnd. For a *step up* PowerTransformer it is exactly the other way round. A collection of equipments (ConductingEquipment, is this a better choice of word?) with the same BaseVoltage is grouped into a https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/VoltageLevel.html[VoltageLevel]. So there is a VoltageLevel associated to (the BaseVoltage of) the primary PowerTransformerEnd. And one associated to the secondary PowerTransformerEnd. Please note, if there is a tertiary PowerTransformerEnd with the same BaseVoltage as the secondary PowerTransformerEnd they form one and the same VoltageLevel (@Arend, is this correct?). A VoltageLevel is not about the number of PowerTransformerEnds, it is about the number of BaseVoltages. And it consists of equipments with the same BaseVoltage.

*Illustration:* Three diagrams with arrow pointing to PowerTransformerEnds and encircling VoltageLevels.
{diagram of transformer with two windings: 00}{diagram of transformer three windings and two VoltageLevels: 08}{diagram of transformer with three windings 08 and three VoltageLevels}

Conceptual model: https://modellen.netbeheernederland.nl/modeling-guidelines/_images/svg-dad2fb976dc069121a3f0a2bb99307e757f40138.svg[Topology without Terminal, ConnectivityNode and without TopologicalNode]

== Connecting Substations
Connecting Substations using ConnectiryNodes, Terminals and TopoligcalNodes. Explaining these are abstractions and they can only exist because of Kirchhoff's Law. 


[comment]
--

A substation uses transformers to step voltage up or down. This is a picture of a transformer. It is a <trafo xyz of type abc> with serial number 123. This is very useful information when you are a purchaser and you need to purchase a replacement transformer. But as a net engineer you might be interested in its function: stepping voltage up or down. This is (in short) the difference between asset perspective and functional perspective. More on this in a later part.


{image of a transformer} {single line diagram of a transformer} {CIM-representation of a transformer}

There are various ways to model a transformer. There is no right or wrong, there is only _useful_ or _not useful_. The same holds for modeling the electrical grid. You can explicitly name every part (asset) of a (power)transformer: https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/VoltageLevel.html[VoltageLevel], https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Substation.html[Substation], https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/PowerTransformer.html[PowerTransformer], https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/PowerTransformerEnd.html[PowerTransformerEnd], https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Terminal.html[Terminal], https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/ConnectivityNode.html[ConnectivityNode], https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/TopologicalNode.html[TopologicalNode], ... When you have a use case, e.g. power consumption of power consumers connected to a specific substation, you have a criterion for what assets are useful to name. This is (in short) the difference between connectivity (naming everything) and topology (naming only useful assets based on a use case). More on this in a later part.
--

[comment]
--
This document explains how to model the electrical grid using https://modellen.netbeheernederland.nl/tc57cim/cim17/index.html[CIM]. It also explains the difference between _asset_ and _functional perspective_ and the difference between _connectivity_ and _topology_.
--

[comment]
--
== Conducting Equipment, Terminals and Connectivity Nodes

In https://modellen.netbeheernederland.nl/tc57cim/cim17/index.html[CIM] https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/ConductingEquipment.html[ConductingEquipment]s are `parts of the AC power system that are designed to carry current or that are conductively connected through terminals.` A https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Terminal.html[Terminal] is an `AC electrical connection point to a piece of conducting equipment. Terminals are connected at physical connection points called connectivity nodes.` Finally, https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/ConnectivityNode.html[ConnectivityNode]s are `points where terminals of AC conducting equipment are connected together with zero impedance.`

You can picture them as a kettlebell on an extension cord. The cast-iron ball-shaped body of the kettlebell is the ConductingEquipment. The round handle attached to it is a ConnectivityNode. And the extension cord is a terminal. The only thing is, there can be multiple handles.

{D2-image of (CE)--has--(T)--is connecting by--(CN)} or simplified: 
{D2-image of (CE)--(T)--(CN)}

With these definitions we will model the electrical grid.
--

[comment]
--

== https://en.wikipedia.org/wiki/Kirchhoff%27s_circuit_laws[Kirchhoff's circuit law] and your electricity bill

Conducting (short distance) without power loss, hence no electricity bill.
Conducting with power loss (power consumption), hence electricity bill.
Linking both with Kirchhoff's law. Tie to connectivity vs topology.
--

---

This document includes text from the https://www.ofgem.gov.uk/decision/long-term-development-statement-direction[LTDS Grid Modelling Guidelines], published under the http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/[Open Government License]

