= Modeling Guidelines
include::partial$include.adoc[]
:author: Ritger Teunissen (Alliander)
:email: ritger.teunissen@alliander.com
:description: This document describes the modeling guidelines for the NBNL Profile Group.
include::partial$header.adoc[]

This document overviews the grid modelling approach and details the grid model
data requirements for data supplied by Dutch transmission and distribution
system operators.

== NBNL grid model
The NBNL grid model scope includes from the 380kV network down to the lower
voltage busbars of primary and secondary substations. It also includes details
of any interconnectors at lower voltages between primary substations needed to
assess the capability of the higher voltage networks. Only equipment that is
normally in service should appear in NBNL modelling.

This document includes text from the
https://www.ofgem.gov.uk/decision/long-term-development-statement-direction[LTDS
Grid Modelling Guidelines], published under the
http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/[Open
Government License]

== Background
Required background reading the modeling guidelines is found
xref::background.adoc[here].

== Patterns
The NBNL Profile Group defines a number of _patterns_ to model use cases. Each
pattern can be used stand-alone, or combined with other patterns.

The following patterns are defined:

include::partial$indexpatterns.adoc[]

== Shapes
Shapes are the fundamental building blocks of the NBNL grid models. They represent a bounded space, the CIM classes are the "building blocks" of a pattern and/or model and grouped based on their NBNL Profiles (like EQ, TP).

The following shapes are defined:

include::partial$indexshapes.adoc[]