= SubgeographicalRegion

:doctype: article
:encoding: utf-8
:lang: en
:toc: right
:numbered!:
:figure-caption!:
:description: This document is part of the modeling guidelines for the NBNL Profile Group.
:url-repo: https://github.com/Netbeheer-Nederland/doc-modeling-guidelines
:domain: modellen.netbeheernederland.nl
:uri: https://{domain}/modeling-guidelines/points
:version: {page-component-display-version}

Author:: mailto:robbert.hardin@alliander.com[Robbert Hardin] (Alliander)
//Editors::
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander) +
//mailto:ritger.teunissen@alliander.com[Ritger Teunissen] (Alliander)https://intranet.alliander.com/event/view/45715445/weten-wat-je-wilt-13-7-april-2026-onlinek

Version:: {version}

Feedback::
https://github.com/Netbeheer-Nederland/doc-modeling-guidelines/issues[Issue on GitHub] (https://github.com/Netbeheer-Nederland/doc-modeling-guidelines[`Netbeheer-Nederland/doc-modeling-guidelines`])

---

== Introduction
This document is part of the grid modelling approach and details the grid model data requirements for data supplied by Dutch transmission and distribution system operators and describes in detail the **SubgeographicalRegion**.

== Definition
A https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/SubGeographicalRegion.html[SubGeographicalRegion] is a subset of a geographical region of a power system network model. The https://modellen.netbeheernederland.nl/object-register/[NBNL Object Register] contains the authoritative list of SubGeographicalRegions within the scope of this object register.


== Core entities
In CIM a SubgeographicalRegion is modelled with a https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/SubGeographicalRegion.html[cim:SubGeographialRegion] associated to a https://modellen.netbeheernederland.nl/tc57cim/cim17/schema/class/Substation.html[cim:Substation].

.CIM:SubGeographicalRegion
[d2,svg,theme=4]
----
include::partial$/vars.d2[]
include::partial$/legend.d2[]
include::partial$/classes.d2[]
include::partial$/connectivity/SubGeographicalRegion.d2[]
----

== Modelling choices
None.

---

This document includes text from the https://www.ofgem.gov.uk/decision/long-term-development-statement-direction[LTDS Grid Modelling Guidelines], published under the http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/[Open Government License]

