grid-rows: 3
grid-columns: 3

vertical-gap: 80
horizontal-gap: 160

CE1: "Conducting Equipment" {class: [grid]}
T1: "Terminal" {class: [grid]}
1_3 {class:[empty]}


2_1 {class:[empty]}
CN: "Connectivity Node" {class: [grid]}
2_3 {class:[empty]}

3_1 {class:[empty]}
T2: "Terminal" {class: [grid]}
CE2: "Conducting Equipment" {class: [grid]}

CE1 -- T1 
T1 -- CN 
CN -- T2 
T2 -- CE2