grid-rows: 3
grid-columns: 5

vertical-gap: 80
horizontal-gap: 160

SS1: "SubStation" {class: [grid]}
PT1: "PowerTransformer" {class: [grid]}
PTE1: "PowerTransformerEnd" {class: [grid]}
BV1: "BaseVoltage" {class: [grid]}
VL1: "VoltageLevel" {class: [grid]}

CN2: "ConnectivityNode" {class: [grid]}
T2: "Terminal" {class: [grid]}
TN: "TopologicalNode" {class: [grid]}
T1: "Terminal" {class: [grid]}
CN1: "ConnectivityNode" {class: [grid]}

VL2: "VoltageLevel" {class: [grid]}
BV2: "BaseVoltage" {class: [grid]}
PTE2: "PowerTransformerEnd" {class: [grid]}
PT2: "PowerTransformer" {class: [grid]}
SS2: "SubStation" {class: [grid]}

SS1 -- PT1 -- PTE1 -- BV1 -- VL1
VL1 -- CN1
CN1 -- T1 -- TN -- T2 -- CN2
CN2 -- VL2
VL2 -- BV2 -- PTE2 -- PT2 -- SS2
