grid-rows: 1
grid-columns: 5

vertical-gap: 80
horizontal-gap: 160

SS: "SubStation" {class: [grid]}
PT: "PowerTransformer" {class: [grid]}
PTE: "PowerTransformerEnd" {class: [grid]}
BV: "BaseVoltage" {class: [grid]}
VL: "VoltageLevel" {class: [grid]}

SS -- PT -- PTE -- BV -- VL
